### ISSUE TITLE
"Time base not set"

### ISSUE THREAD

**Issue by jwadsager** [iizukanao/picam#10]
When I try to record under Arch Linux I get:

[jakob@raspi recordings]$ picam --alsadev hw:1,0 &
[1] 496
[jakob@raspi recordings]$ configuring devices
capturing started

[jakob@raspi recordings]$ touch hooks/start_record
disk_usage=6% [jakob@raspi recordings]$ [mpegts @ 0xb1e940f0] time base not set
avformat_write_header failed

[1]+  Exit 1                  picam --alsadev hw:1,0
[jakob@raspi recordings]$

I have used the packages from here: http://ftp.tuebingen.mpg.de/pub/kyb/towolf/raspberry-camera-streaming/resources/

**Comment by iizukanao** [comment]
Hi, can you try again with the latest master?
If it still fails, please give me the output of picam command with `--verbose` option.
Thanks.

**Comment by jwadsager** [comment]
It seems to work now.
