### ISSUE TITLE
Login for the "picam preinstalled Raspbian image" missing

### ISSUE THREAD

**Issue by Maxos1984** [iizukanao/picam#11]
Hello, 
I downloaded your preinstalled version of picam and at the first start it askes me for a login. Can you help me with the login and password?
Thx in advance.

Max

**Comment by iizukanao** [comment]
It's the same as Raspbian.
user: pi
password: raspberry

**Comment by Maxos1984** [comment]
Oh, I'm so sorry. I tried that many times but as the German Keyboard has Z and Y switched, it always failed. Thank you you for your fast help!
