### ISSUE TITLE
How do you think, is it possible to create python bindings to picam?

### ISSUE THREAD

**Issue by yurket** [iizukanao/picam#12]
It would be great to have some more high-level way to start\stop recording. So I consider to create python bindings for picam, but I've never done it before. So maybe you can give me some directions how to do it?
Thanks!

**Comment by iizukanao** [comment]
Hi, sorry for the delay.
If you want to just start/stop recording from Python script, create empty start_record and stop_record files in hooks directory.

If you want to control picam directly, it needs some work on picam codebase to make it accessible from outside. Also, I don't know how to create Python binding for C but it must be possible.

**Comment by yurket** [comment]
Thanks for your reply!
For now creating files start_record\stop_record is enough, but I may need to control picam directly in the future.

**Comment by iizukanao** [comment]
OK, I will create picam API.
Thanks for the suggestion!

**Comment by rpastorvargas** [comment]
Any advances on picam python API?

Regards,
rafael

**Comment by iizukanao** [comment]
@rpastorvargas Not yet.

**Comment by rpastorvargas** [comment]
Ok, thanks for the information. Maybe you can request help on this, probably i'll could help you with some issues and implementation.

regards,
rafael
