### ISSUE TITLE
Dropped frames every 15-30 seconds

### ISSUE THREAD

**Issue by feacluster** [iizukanao/picam#132]
I am using a raspberry pi 3B with picam 1.4.7. Seems every 15-30 seconds I experience dropped frames. The video goes still for a split second then jumps ahead. I have tried both these commands with picam:

picam --alsadev hw:1,0 
picam --alsadev hw:1,0 --vfr --maxfps 30 --minfps 10 --shutter 20000 -v 1000000 -w 1024 -h 768

I need to record upto 60 minutes, so can not use the /dev/shm folder. These are being written to the micro SD card. 

You can watch an example of it here:

https://www.youtube.com/watch?v=REf9hh1kklo

Is there some gpu setting I need to play around with?

**Comment by feacluster** [comment]
Update: I tried playing around with --mode and it seems to give fewer dropped frames with some modes.. Mode 7 seems best but the field of view is smaller and seems the quality is not so sharp..
Any other suggestions to try?

**Comment by iizukanao** [comment]
Not utilizing /dev/shm might be the cause of such issue. Can you add `--verbose` option to your picam command then provide me a full output?

**Comment by feacluster** [comment]
Thanks, I switched it back to /dev/shm and now the dropped frames issue has mostly gone away . Initially I thought using /dev/shm would limit the video size to the size of /dev/shm . But seems that is not the case? Looks like picam writes the video file back to the SD card so the size of the SD card is the limiting factor. Is that correct?

**Comment by iizukanao** [comment]
@feacluster Sorry for the late reply. Yes, you're correct. /dev/shm is used only for write buffering (reduces the frequency of writes to SD card).

**Comment by feacluster** [comment]
Just another update. I switched to a different SD card and now experience zero dropped frames. This is the one I used:

Samsung (MB-ME32GA/AM) 32GB 95MB/s (U1) microSDHC EVO Select Memory Card
