### ISSUE TITLE
New AWB algorithm in Raspbian

### ISSUE THREAD

**Issue by 98Matthias** [iizukanao/picam#137]
Hi,

after upgrading to the latest firmware Raspbian uses an new AWB algorithm and NoIR pictures are purple by default.
You can use raspistill -awb greyworld to get a picture in greyscale.
Is there a way to use this with picam?

Matthias

**Comment by iizukanao** [comment]
@98Matthias I apologize for not responding earlier. `--wb greyworld` option is added in picam version 1.4.9. Thank you for your suggestion!
