### ISSUE TITLE
Audio Noise Problem

### ISSUE THREAD

**Issue by bill-connelly** [iizukanao/picam#148]
Whether I stream the audio, or record a video directly I get the weird noise, pulsing at 1 Hz (which you can't really hear in the sample below). The microphone is fine when I test it on other PCs. 

I tried with various different sample rates apart from the default  (e.g. --samplerate 44100 ) and they never work.

I uploaded a sample here just in case that helps anyone. https://youtu.be/J2GmQLPIvHs

And this is in a perfectly quiet room. There is no fan on the Pi or in the same room.

No errors when I run in --verbose. 

Not a very helpful bug report, but it's really annoying. Let me know if I can run any other tests. Thanks.

EDIT: I see that that the frequency of the 1 Hz pulse noise is proportional to the number of people logging in, i.e. with 1 person logging in it is at 1 Hz, with 2 people logging in it is approximately 2 times a second, and with 3 people logging in you get 3 pulses per second.

**Comment by lucasrangit** [comment]
Do you get the same noise when using `arecord`?

**Comment by iizukanao** [comment]
Closing due to no response from the issue reporter
