### ISSUE TITLE
select profile

### ISSUE THREAD

**Issue by madsheep** [iizukanao/picam#15]
Hi 

I've noticed you are using baseline 3.1 profile for h264 only (I think the comments in the code mentioned that main/high profiles are not working on android) 

Would it be possible to add an option to select profile when you need something else than baseline?

**Comment by iizukanao** [comment]
Thanks for the suggestion. `--avcprofile` and `--avclevel` options are now added.

**Comment by madsheep** [comment]
Thanks! Works beautifully :)
