### ISSUE TITLE
./picam: error while loading shared libraries: libbrcmGLESv2.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by akashmiami** [iizukanao/picam#151]
Hi, I am getting this error on On Raspberry Pi Buster 64-bit using picam-1.4.9-binary.tar.xz. On Raspberry Pi Buster 32-bit, I use picam without an issue.
My Raspberry Pi 's uname -a is:  5.10.5-v8+ #1392 SMP PREEMPT Sat Jan 9 18:56:30 GMT 2021 aarch64 GNU/Linux
If anyone has an insight into how to solve this, will be greatly appreciated.

Thanks.

**Comment by iizukanao** [comment]
Sorry for the late reply. Looks like OpenMAX (the library picam depends on) is not available on 64-bit OS. Please use 32-bit OS.

**Comment by tacocat75** [comment]
Having this issue on raspian bullseye 32bit
