### ISSUE TITLE
EXT-X-TARGETDURATION is sometimes 0 when it shouldn't be

### ISSUE THREAD

**Issue by marler8997** [iizukanao/picam#152]
I'm running into a problem where the `hls.js` client crashes because of an invalid "targetduration" entry in the HLS manifest file `index.m3u8` coming from picam.

When the camera captures alot of movement, the video files start to get very short in time, and eventually I get a manifest with an `EXT-X-TARGETDURATION` of 0.  The `hls.js` project asserts a "manifest parsing error" whenever it receives a targetduration of 0, as you can see here: https://github.com/video-dev/hls.js/blob/v1.0.0-beta.3/src/loader/playlist-loader.ts#L676

According to the RFC (https://tools.ietf.org/html/rfc8216#section-4.3.3.1) `EXT-X-TARGETDURATION` specifies the "maximum Media Segment duration".  However, it seems that picam is setting this value to something more like the average rounded to the nearest integer (see https://github.com/iizukanao/picam/blob/v1.4.9/httplivestreaming.c#L161).

Here is an example of one of the erroneous manifest files from picam:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:0
#EXT-X-MEDIA-SEQUENCE:3096
#EXT-X-ALLOW-CACHE:NO
#EXTINF:0.19058,
3091.ts
#EXTINF:1.09227,
3092.ts
#EXTINF:1.22524,
3093.ts
#EXTINF:0.09422,
3094.ts
#EXTINF:0.12587,
3095.ts
#EXTINF:0.12516,
3096.ts
```

Interestingly, I actually think there is a problem both with picam but also with `hls.js`.  The spec actually says 

"The EXTINF duration of each Media Segment in the Playlist file, when rounded to the nearest integer, MUST be less than or equal to the target duration"

So the target duration of the example manifest file above should still be `1`, however, you could imagine a theoretical manifest file where all the values are less than `0.5`, which would mean the nearest integer is in fact 0.  So `hls.js` should probably still handle a `0` value, but picam seems to be setting the value to `0` when it shouldn't be.  I think this can be fixed with a simple change to `calc_target_duration` by finding the maximum duration and then rounding, rather then rounding the average duration.

**Comment by iizukanao** [comment]
@marler8997 Thank you for the detailed explanation!
