### ISSUE TITLE
Keep record before start

### ISSUE THREAD

**Issue by NicolasDesvignes** [iizukanao/picam#157]
Hi,
i try picam, it look like what i want, but i have small problem.

i wrote a python script to put the start_record file when i press a button. (and to write the stop_record later)
I work, but in the video, a have 5-6s recorded before i press the button, and i don't find how to solve it.
I use the last picam 1.4.9 on raspeberry pi 3 with raspberry hd camera, running raspbian (raspberry pi os) up to date.

**Comment by iizukanao** [comment]
@NicolasDesvignes Sorry for the late response. Please use `--recordbuf 1` option.

**Comment by NicolasDesvignes** [comment]
Oh thanks, 
it work !
