### ISSUE TITLE
Sensor and subtitle

### ISSUE THREAD

**Issue by planet4** [iizukanao/picam#160]
First of all thanks for the work with Picam. I am right now using RPI Cam control for my Birdbox with camera. But have set up Picam to build another one. I am right now testing so it works and have started with text overlay and subtitles.

My question is if it would be possible to add a sensor like DHT22 to display temperature or humidity in the text overlay? That would look very good.

**Comment by iizukanao** [comment]
Sorry for the late response. Yes, you can display any text with `hooks/subtitle`. Read sensor values with some script (bash, Python, etc.) and put it into `hooks/subtitle`.
