### ISSUE TITLE
Picam forces 'AVC High Profile Level 4' regardless of settings, forcing FPS to 22 

### ISSUE THREAD

**Issue by shadowpho** [iizukanao/picam#161]
For some reason whenever I start picam 1.4.11 (latest) it defaults to 'AVC High Profile Level 4'. As a result the raspberry pi 4 only records at 22 FPS. 

Here is my /var/log/picam.log  (here is where it mentions AVC high profile level 4)
[picam.log](https://github.com/iizukanao/picam/files/6505453/picam.log)

Here is my run_me script:
`sudo bash /home/shadowpho/make_dirs.sh                                                                                                                                                       sudo /home/shadowpho/picam/picam -o /run/shm/hls --avcprofile main -w 1920 -h 1080 --verbose --time --timeformat "%a %b %d %H:%M:%S %Z" --alsadev hw:1,0 > /var/log/picam.log 2>&1  
`

Any thoughts?

**Comment by iizukanao** [comment]
Sorry for the late reply. picam version 2.0.0 supports 1920x1080. If you are still interested, please give it a try.
