### ISSUE TITLE
Error building picam - error: AVStream has no member named codec

### ISSUE THREAD

**Issue by wef42** [iizukanao/picam#163]
I have a raspberry Pi 4B.  I am following the instructions in the BUILDING.md file.

I found to compile ffmpeg I needed to add the --extra-ldflags="-latomic" to the configure command line

When compiling picam I got an error where the AVCodecContext structure was undefined so I added #include <libavcodec/avcodec.h> to the mpegts.c.

The compile now gets an error:-
mpegts.c:28:48: error: 'AVStream' {aka 'struct AVStream'} has no member named 'codec'
   video_codec_ctx                = video_stream->codec;

Looking at the AVStream structure definition there is in fact no codec member so I am not sure how to proceed.  I suspect that the version of ffmpeg needs to maybe be an older version but are not sure which one

**Comment by iizukanao** [comment]
Sorry for the late response. This has been fixed.
