### ISSUE TITLE
Switch between two cameras

### ISSUE THREAD

**Issue by 98Matthias** [iizukanao/picam#164]
Hi,

the Compute Module IO Board has two CSI-2 camera interfaces.
The supplied camera applications raspivid and raspistill have the -cs (--camselect) option to specify which camera should be used.

Is it possible to add this parameter?

Greetings,
Matthias

**Comment by iizukanao** [comment]
Sorry for the late reply. Yes, it is possible to add the parameter for camera selection. If you are still interested, please let me know.

**Comment by 98Matthias** [comment]
Yes, that would be great! I have read that the option changed to --camera in libcamera.

![image](https://user-images.githubusercontent.com/56916751/177746329-0da4ba82-18c6-4259-9a3d-a5cdf0822798.png)

**Comment by iizukanao** [comment]
Thanks for your comment!

**Comment by iizukanao** [comment]
@98Matthias I have built a picam binary that supports `--camera` option. Can you check if it works?
[picam-2.0.1-armv7l.tar.gz](https://github.com/iizukanao/picam/files/9078385/picam-2.0.1-armv7l.tar.gz)

Usage:
```
--camera <num>      Choose the camera to use. Use --query to list the cameras.
```

**Comment by 98Matthias** [comment]
Thanks a lot! I will be able to test it in a few days 👍

**Comment by 98Matthias** [comment]
It works perfectly. Thanks for your effort!

**Comment by iizukanao** [comment]
@98Matthias Thank you for your feedback! I will release it as version 2.0.1 soon.
