### ISSUE TITLE
Use Arducam 

### ISSUE THREAD

**Issue by bxmatus** [iizukanao/picam#168]
Hi, 

i'm trying to use Arducam 16MP (imx519) but picam does not like it:

error: failed to create camera component: 0xffffffff
Have you enabled camera via raspi-config or /boot/config.txt?

Camera is working k with using "libcamera-jpg" ...

thanks

m.

**Comment by iizukanao** [comment]
I believe this problem has been fixed in picam version 2.0.0. Please open a new issue if it is not solved yet.
