### ISSUE TITLE
Lagging in video and microphone error: buffer overrun

### ISSUE THREAD

**Issue by furkanbalikci** [iizukanao/picam#169]
Hello @iizukanao , 
I am trying to record audio and video with picam. I am using Rpi Zero as device. I am using picamera for video and external mems microphone for audio. There are lags in the test videos that I am moving. And I keep getting the "microphone error: buffer overrun" error. I'm not sure if these two are related.
What I really need is to be able to record video and audio synchronously.
Do you have any suggestions for these topics?
Thanks.

**Comment by iizukanao** [comment]
Hello @furkanbalikci, thanks for your feedback.
It seems that the data transfer rate from the microphone is lower than it should be. Please use the `top` or `glances` commands to make sure the Pi is not doing too much work while recording (check CPU, SWAP, and disk I/O).

Btw, how many audio channels can your microphone record?

**Comment by furkanbalikci** [comment]
Hi @iizukanao , thanks for your quick answer. I bough a new voice card, its using same mic. For now I don't get microphone error but lag problem is still going on. 
Also I checked  CPU, its around %50, SWAP is %0, and for disk I/O i used iostat -d 2 command output is bellow. After new voice card I use alsa command with hw:0 not hw:0,0. its look better but I think main problem is frame dropping, what can I do for this problem. Its like urgent situation, I am waiting your reply. 

Thanks for everything.

**Comment by iizukanao** [comment]
@furkanbalikci Hmm, I have no idea why that happens. How many seconds of lag are there? Are you experiencing both lag (video and audio are out of sync) and frame dropping (intermittent sound) at the same time? Can you record audio with `arecord` command without problem?

**Comment by furkanbalikci** [comment]
@iizukanao thanks for quick answer. Now I tested at outside. I walked with like 10 minutes. Now I have 2 situation. 
1) The quality of video looks bad. I am using default (1280/720 alsa fps is defauld)  but its look like 480p. But  when I not moving much better. 
2) Still sometimes frame is dropping. I tried fps with 15,25 and it did not effect the frame dropping. 
What could be causing this? Could the sound have an effect on this?

**Comment by furkanbalikci** [comment]
@iizukanao I solved the video resolution drop problem by increasing the bitrate. But video stuttering is still present (I defined this event as framedropping earlier). Please help with this :(

**Comment by iizukanao** [comment]
@furkanbalikci If you don't see frame drops in the preview (`-p` option), maybe the SD card write performance is too slow or some other program is overloading the disk I/O and not recording the video properly. If you still see `microphone error` message, there may be a problem with your ALSA configuration or hardware.

**Comment by furkanbalikci** [comment]
Hello again @iizukanao, this is my full verbose output. As you can see sometime is dropping. Does this mean anything to you? The camera stays in a fixed position meanwhile.



pi@raspberrypi:~/picam $ ./picam --alsadev hw:0 --videobitrate 5000000 --time --verbose
video_width=1280
video_height=720
video_fps=30.000000
fr_q16=1966080
video_pts_step=3000
video_gop_size=30
video_rotation=0
video_hflip=0
video_vflip=0
video_bitrate=5000000
video_avc_profile=constrained_baseline
video_avc_level=3.1
video_qp_min=-1
video_qp_max=-1
video_qp_initial=-1
video_slice_dquant=-1
alsa_dev=hw:0
audio_channels=1
audio_sample_rate=48000
audio_bitrate=40000
audio_volume_multiply=1.000000
is_hlsout_enabled=0
is_hls_encryption_enabled=0
hls_keyframes_per_segment=1
hls_number_of_segments=3
hls_encryption_key_uri=stream.key
hls_encryption_key=0x75b0a81de17487c88a47507a7e1fdf73
hls_encryption_iv=0x000102030405060708090a0b0c0d0e0f
hls_output_dir=/run/shm/video
rtsp_enabled=0
rtsp_video_control_path=/tmp/node_rtsp_rtmp_videoControl
rtsp_audio_control_path=/tmp/node_rtsp_rtmp_audioControl
rtsp_video_data_path=/tmp/node_rtsp_rtmp_videoData
rtsp_audio_data_path=/tmp/node_rtsp_rtmp_audioData
tcp_enabled=0
tcp_output_dest=
auto_exposure_enabled=0
auto_exposure_threshold=5.000000
is_vfr_enabled=0
white_balance=auto
exposure_control=auto
awb_red_gain=0.000000
awb_blue_gain=0.000000
metering=average
manual_exposure_compensation=0
exposure_compensation=0.000000
manual_exposure_aperture=0
exposure_aperture=0
manual_exposure_shutter_speed=0
exposure_shutter_speed=0
manual_exposure_sensitivity=0
exposure_sensitivity=0
roi_left=0.000000
roi_top=0.000000
roi_width=1.000000
roi_height=1.000000
min_fps=-1.000000
max_fps=-1.000000
is_timestamp_enabled=1
timestamp_format=%a %b %d %l:%M:%S %p
timestamp_layout=15
timestamp_horizontal_margin=10
timestamp_vertical_margin=10
is_timestamp_abs_pos_enabled=0
timestamp_pos_x=0
timestamp_pos_y=0
timestamp_text_align=1
timestamp_font_name=FreeMono:style=Bold
timestamp_font_file=
timestamp_font_face_index=(null)
timestamp_font_points=14.000000
timestamp_font_dpi=96
timestamp_color=ffffff
timestamp_stroke_color=000000
timestamp_stroke_width=1
timestamp_letter_spacing=0
is_preview_enabled=0
is_previewrect_enabled=0
preview_x=0
preview_y=0
preview_width=0
preview_height=0
preview_opacity=255
blank_background_color=0x0
is_audio_preview_enabled=0
audio_preview_dev=plughw:0,0
record_buffer_keyframes=5
state_dir=state
hooks_dir=hooks
configuring devices
exposure control: auto
setting exposure:
  eMetering: 0
  xEVCompensation: 0
  nApertureFNumber: 0
  bAutoAperture: 0
  nShutterSpeedMsec: 0
  
  bAutoShutterSpeed: 1
  nSensitivity: 0
  bAutoSensitivity: 1
Set video_encode state to idle
Enable port buffers for camera 71
Enable port buffers for video_encode 200
Enable port buffers for video_encode 201
Set camera state to executing
Set video_encode state to executing
opening ALSA device for capture: hw:0
cannot use mono audio; trying stereo
final audio_channels: 2
sample_rate: 48000
nb_samples: 1024
sample_fmt: 1
audio_codec_ctx->channel_layout: 3
av_frame->channel_layout: 3
audio_codec_ctx->channels: 2
av_frame->channels: 2
allocated 4096 bytes for audio samples
audio_pts_step_base: 1920
actual sample rate=48000 dir=0
failed to set buffer size for microphone: buffer_size=4096 multiply=100
trying smaller buffer size for microphone: buffer_size=4096 multiply=50
failed to set buffer size for microphone: buffer_size=4096 multiply=50
trying smaller buffer size for microphone: buffer_size=4096 multiply=25
microphone: buffer size: 102400 frames (channels=2 buffer_size=4096 multiply=25)
microphone: setting period size to 1024
actual_period_size=1024 dir=0
audio capture device:
Hardware PCM card 0 'seeed-2mic-voicecard' device 0 subdevice 0
Its setup is:
  stream       : CAPTURE
  access       : MMAP_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 48000
  exact rate   : 48000 (48000/1)
  msbits       : 16
  buffer_size  : 102400
  period_size  : 1024
  period_time  : 21333
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 1024
  period_event : 0
  start_threshold  : 1
  stop_threshold   : 102400
  silence_threshold: 0
  silence_size : 0
  boundary     : 1677721600
  appl_ptr     : 0
  hw_ptr       : 0
start capturing video
waiting for the first video buffer
start capturing audio
[microphone started]capturing started
..e(0x0).[NAL7].vSPEED_UP(10440).............................. 31.33 fps k=1 a-v=6030 c-a=-1001 u=1 d=0 pts=103680
................vNORMAL.............. 30.19 fps k=2 a-v=2100 c-a=378 u=1 d=0 pts=189900
.............................. 30.25 fps k=3 a-v=2340 c-a=128 u=1 d=0 pts=279900
.............................. 30.05 fps k=4 a-v=2580 c-a=38 u=1 d=0 pts=369900
.............................. 30.09 fps k=5 a-v=2820 c-a=-248 u=1 d=0 pts=459900
.............................. 30.11 fps k=6 a-v=3060 c-a=-533 u=1 d=0 pts=549900
.............................. 30.13 fps k=7 a-v=3300 c-a=-898 u=1 d=0 pts=639900
.............................. 30.18 fps k=8 a-v=3540 c-a=-1002 u=1 d=0 pts=733440
.............................. 30.24 fps k=9 a-v=1860 c-a=257 u=1 d=0 pts=819900
.............................. 30.17 fps k=10 a-v=2100 c-a=221 u=1 d=0 pts=909900
.............................. 30.10 fps k=11 a-v=2340 c-a=-37 u=1 d=0 pts=999900
.............................. 30.09 fps k=12 a-v=2580 c-a=-257 u=1 d=0 pts=1089900
.............................. 30.15 fps k=13 a-v=2820 c-a=-665 u=1 d=0 pts=1179900
.............................. 30.10 fps k=14 a-v=3060 c-a=-951 u=1 d=0 pts=1272960
.............................. 30.19 fps k=15 a-v=1380 c-a=414 u=1 d=0 pts=1359900
.............................. 30.24 fps k=16 a-v=1620 c-a=96 u=1 d=0 pts=1449900
.............................. 30.01 fps k=17 a-v=1860 c-a=104 u=1 d=0 pts=1539900
.............................. 30.12 fps k=18 a-v=2100 c-a=-191 u=1 d=0 pts=1629900
.............................. 30.10 fps k=19 a-v=2340 c-a=-478 u=1 d=0 pts=1719900
.............................. 30.09 fps k=20 a-v=2580 c-a=-763 u=1 d=0 pts=1809900
.............................. 30.08 fps k=21 a-v=2820 c-a=-999 u=1 d=0 pts=1902720
.............................. 30.20 fps k=22 a-v=1140 c-a=341 u=1 d=0 pts=1989900
.............................. 30.21 fps k=23 a-v=1380 c-a=86 u=1 d=0 pts=2079900
.............................. 30.00 fps k=24 a-v=1620 c-a=67 u=1 d=0 pts=2169900
.............................. 30.11 fps k=25 a-v=1860 c-a=-264 u=1 d=0 pts=2259900
.............................. 30.02 fps k=26 a-v=2100 c-a=-300 u=1 d=0 pts=2349900
.............................. 30.06 fps k=27 a-v=2340 c-a=-205 u=1 d=0 pts=2439900
.............................. 30.44 fps k=28 a-v=2580 c-a=-1027 u=1 d=0 pts=2532480
..........................disk_usage=25% ....removed existing file: /tmp/testo.mp4
 29.71 fps k=29 a-v=2820 c-a=-128 u=1 d=0 pts=2619900
.start rec to /tmp/testo.mp4
..............caught up............... 30.55 fps k=30 a-v=1140 c-a=386 u=1 d=0 pts=2709900
.............................. 30.31 fps k=31 a-v=1380 c-a=-67 u=1 d=0 pts=2799900
.............................. 30.10 fps k=32 a-v=1620 c-a=-333 u=1 d=0 pts=2889900
.............................. 30.11 fps k=33 a-v=1860 c-a=-617 u=1 d=0 pts=2979900
.............................. 30.08 fps k=34 a-v=2100 c-a=-863 u=1 d=0 pts=3069900
..........FvSPEED_UP(14340)..............vR47040...... 18.16 fps k=35 a-v=9900 c-a=184 u=2 d=0 pts=3209940
.............................. 30.13 fps k=36 a-v=5640 c-a=-196 u=2 d=0 pts=3304440
...........vNORMAL................... 30.09 fps k=37 a-v=4380 c-a=-478 u=2 d=0 pts=3395940
.............................. 30.64 fps k=38 a-v=2700 c-a=-448 u=2 d=0 pts=3485940
.............................. 30.17 fps k=39 a-v=2940 c-a=-954 u=2 d=0 pts=3575940
..............................F 29.79 fps k=40 a-v=3180 c-a=-275 u=2 d=0 pts=3665940
.............................. 28.79 fps k=41 a-v=7260 c-a=-359 u=2 d=0 pts=3755940
.............................. 30.09 fps k=42 a-v=7500 c-a=-619 u=2 d=0 pts=3845940
.............................. 30.12 fps k=43 a-v=7740 c-a=-955 u=2 d=0 pts=3935940
.............................. 30.05 fps k=44 a-v=7980 c-a=-1052 u=2 d=0 pts=4033920
.............................. 30.22 fps k=45 a-v=6300 c-a=235 u=2 d=0 pts=4115940
.............................. 30.03 fps k=46 a-v=6540 c-a=139 u=2 d=0 pts=4205940
.............................F.vR45180 21.19 fps k=47 a-v=0 c-a=-867 u=2 d=0 pts=4341120
.............................. 31.36 fps k=48 a-v=-3600 c-a=-970 u=2 d=0 pts=4431120
.............................. 30.18 fps k=49 a-v=-5280 c-a=761 u=2 d=0 pts=4521120
.............................. 30.23 fps k=50 a-v=-5040 c-a=165 u=2 d=0 pts=4611120
.............................. 30.03 fps k=51 a-v=-4800 c-a=104 u=2 d=0 pts=4701120
.............................. 30.10 fps k=52 a-v=-4560 c-a=-172 u=2 d=0 pts=4791120
.................F.vSPEED_UP(24000)............ 23.78 fps k=53 a-v=16770 c-a=316 u=3 d=0 pts=4883070
.............................. 30.20 fps k=54 a-v=12510 c-a=92 u=3 d=0 pts=4977570
.............................. 30.09 fps k=55 a-v=8250 c-a=-172 u=3 d=0 pts=5072070
.............................. 30.07 fps k=56 a-v=3990 c-a=-455 u=3 d=0 pts=5166570
........vNORMAL...................... 30.06 fps k=57 a-v=3180 c-a=-712 u=3 d=0 pts=5257620
.............................. 30.08 fps k=58 a-v=3420 c-a=-970 u=3 d=0 pts=5347620
.........F.vSPEED_UP(31020).................... 22.48 fps k=59 a-v=31230 c-a=-1108 u=4 d=0 pts=5472000
.............................. 29.73 fps k=60 a-v=26970 c-a=-289 u=4 d=0 pts=5535270
.............................. 30.17 fps k=61 a-v=22710 c-a=-773 u=4 d=0 pts=5629770
.............................. 30.08 fps k=62 a-v=18450 c-a=-981 u=4 d=0 pts=5724270
.............................. 30.21 fps k=63 a-v=12270 c-a=276 u=4 d=0 pts=5818770
.............................F.vR182880 10.19 fps k=64 a-v=0 c-a=1046 u=4 d=0 pts=6096000
....vNORMAL.......................... 30.39 fps k=65 a-v=-210 c-a=-2 u=4 d=0 pts=6186450
.............................. 30.05 fps k=66 a-v=30 c-a=-96 u=4 d=0 pts=6276450
.............................. 30.07 fps k=67 a-v=270 c-a=-282 u=4 d=0 pts=6366450
....trying to recover from error
microphone error: buffer overrun
[microphone started]F...vSPEED_UP(9990).......................  5.18 fps k=68 a-v=2670 c-a=425593 u=5 d=0 pts=6460050
.vNORMAL............................. 30.06 fps k=69 a-v=2910 c-a=425402 u=5 d=0 pts=6550050
.............................. 30.13 fps k=70 a-v=3150 c-a=424975 u=5 d=0 pts=6640050
.............................. 30.16 fps k=71 a-v=3390 c-a=424911 u=5 d=0 pts=6733440
.............................. 30.14 fps k=72 a-v=1710 c-a=426748 u=5 d=0 pts=6820050
.............................. 30.33 fps k=73 a-v=1950 c-a=425857 u=5 d=0 pts=6910050
.......FvSPEED_UP(30870)....................... 23.03 fps k=74 a-v=25470 c-a=426221 u=6 d=0 pts=7003650
.............................. 30.17 fps k=75 a-v=21210 c-a=425710 u=6 d=0 pts=7098150
.............................. 30.10 fps k=76 a-v=16950 c-a=425421 u=6 d=0 pts=7192650
.............................. 30.14 fps k=77 a-v=12690 c-a=424993 u=6 d=0 pts=7287150
.............................. 29.74 fps k=78 a-v=8430 c-a=425892 u=6 d=0 pts=7381650
...........................F... 23.24 fps k=79 a-v=31050 c-a=425207 u=6 d=0 pts=7476150
.............................. 30.37 fps k=80 a-v=24870 c-a=426037 u=6 d=0 pts=7570650
.............................. 27.41 fps k=81 a-v=30210 c-a=424968 u=6 d=0 pts=7665150
.............................. 31.01 fps k=82 a-v=22110 c-a=425853 u=6 d=0 pts=7759650
.............................. 30.11 fps k=83 a-v=17850 c-a=425536 u=6 d=0 pts=7854150
.............................. 30.11 fps k=84 a-v=13590 c-a=425209 u=6 d=0 pts=7948650
................F.............. 25.81 fps k=85 a-v=22770 c-a=426668 u=6 d=0 pts=8043150
.............................. 30.16 fps k=86 a-v=18510 c-a=426278 u=6 d=0 pts=8137650
.............................. 30.30 fps k=87 a-v=14250 c-a=425834 u=6 d=0 pts=8232150
.............................. 30.08 fps k=88 a-v=9990 c-a=425583 u=6 d=0 pts=8326650
.............................. 30.07 fps k=89 a-v=5730 c-a=425352 u=6 d=0 pts=8421150
...................vNORMAL........... 30.12 fps k=90 a-v=3270 c-a=424994 u=6 d=0 pts=8513850
............FvR97830.................. 14.58 fps k=91 a-v=-240 c-a=426132 u=6 d=0 pts=8701680
.............................. 30.07 fps k=92 a-v=0 c-a=425902 u=6 d=0 pts=8791680
.............................. 30.03 fps k=93 a-v=240 c-a=425858 u=6 d=0 pts=8881680
.............................. 30.09 fps k=94 a-v=480 c-a=425598 u=6 d=0 pts=8971680
.............................. 30.07 fps k=95 a-v=720 c-a=425395 u=6 d=0 pts=9061680
.............................. 30.15 fps k=96 a-v=960 c-a=425001 u=6 d=0 pts=9151680
..........F.................... 29.11 fps k=97 a-v=3120 c-a=425817 u=6 d=0 pts=9241680
.............................. 30.07 fps k=98 a-v=3360 c-a=425643 u=6 d=0 pts=9331680
.............................. 30.08 fps k=99 a-v=3600 c-a=425425 u=6 d=0 pts=9421680
.............................. 30.16 fps k=100 a-v=3840 c-a=424988 u=6 d=0 pts=9511680
.............................. 30.16 fps k=101 a-v=4080 c-a=424890 u=6 d=0 pts=9605760
.............................. 30.18 fps k=102 a-v=4320 c-a=424808 u=6 d=0 pts=9696000
.........F.vR344880....................  6.31 fps k=103 a-v=-4320 c-a=426880 u=6 d=0 pts=10126560
.............................. 30.20 fps k=104 a-v=-4080 c-a=426283 u=6 d=0 pts=10216560
.............................. 30.24 fps k=105 a-v=-3840 c-a=426047 u=6 d=0 pts=10306560
.............................. 30.07 fps k=106 a-v=-3600 c-a=425906 u=6 d=0 pts=10396560
.............................. 30.06 fps k=107 a-v=-3360 c-a=425757 u=6 d=0 pts=10486560
................F.............. 28.20 fps k=108 a-v=2640 c-a=425779 u=6 d=0 pts=10576560
.............................. 30.06 fps k=109 a-v=2880 c-a=425639 u=6 d=0 pts=10666560
.............................. 29.83 fps k=110 a-v=3120 c-a=426191 u=6 d=0 pts=10756560
.............................. 30.60 fps k=111 a-v=3360 c-a=424994 u=6 d=0 pts=10846560
.............................. 30.21 fps k=112 a-v=3600 c-a=424834 u=6 d=0 pts=10940160
.............................. 30.18 fps k=113 a-v=1920 c-a=426278 u=6 d=0 pts=11026560
..............F.......vSPEED_UP(9960)......... 29.25 fps k=114 a-v=4500 c-a=425174 u=7 d=0 pts=11118060
..........vNORMAL.................... 30.08 fps k=115 a-v=3390 c-a=424948 u=7 d=0 pts=11212800
..........trying to recover from error
microphone error: buffer overrun
[microphone started]....................  7.04 fps k=116 a-v=3630 c-a=718447 u=7 d=0 pts=11299410
.....F.vSPEED_UP(18270)........................ 26.52 fps k=117 a-v=11640 c-a=718727 u=8 d=0 pts=11393160
.............................. 30.09 fps k=118 a-v=7380 c-a=718421 u=8 d=0 pts=11487660
.............................. 30.10 fps k=119 a-v=3120 c-a=718131 u=8 d=0 pts=11582160
......vNORMAL........................ 30.11 fps k=120 a-v=2610 c-a=717816 u=8 d=0 pts=11672910
.............................. 30.09 fps k=121 a-v=2850 c-a=717567 u=8 d=0 pts=11765760
.............................. 30.16 fps k=122 a-v=1170 c-a=718939 u=8 d=0 pts=11852910
.F............................. 29.18 fps k=123 a-v=5250 c-a=718042 u=8 d=0 pts=11942910
.............................. 30.08 fps k=124 a-v=5490 c-a=717780 u=8 d=0 pts=12032910
.............................. 30.21 fps k=125 a-v=5730 c-a=717509 u=8 d=0 pts=12128640
.............................. 30.20 fps k=126 a-v=4050 c-a=718927 u=8 d=0 pts=12212910
.............................. 30.25 fps k=127 a-v=4290 c-a=718627 u=8 d=0 pts=12302910
.............................. 30.05 fps k=128 a-v=4530 c-a=718493 u=8 d=0 pts=12392910
.FvSPEED_UP(36090)............................. 22.53 fps k=129 a-v=30990 c-a=717646 u=9 d=0 pts=12487410
.............................. 30.20 fps k=130 a-v=24810 c-a=718950 u=9 d=0 pts=12581910
.............................. 30.25 fps k=131 a-v=20550 c-a=718690 u=9 d=0 pts=12676410
.............................. 30.08 fps k=132 a-v=16290 c-a=718453 u=9 d=0 pts=12770910
.............................. 30.06 fps k=133 a-v=12030 c-a=718270 u=9 d=0 pts=12865410
.........F........vR46950.........vR48600.... 13.85 fps k=134 a-v=18120 c-a=717606 u=9 d=0 pts=13055160
.............................. 30.26 fps k=135 a-v=11940 c-a=718780 u=9 d=0 pts=13149660
.............................. 30.06 fps k=136 a-v=7680 c-a=718593 u=9 d=0 pts=13244160
.............................. 30.10 fps k=137 a-v=3420 c-a=718369 u=9 d=0 pts=13338660
...........vNORMAL................... 30.10 fps k=138 a-v=2160 c-a=718077 u=9 d=0 pts=13430160
.............................. 30.06 fps k=139 a-v=2400 c-a=717894 u=9 d=0 pts=13520160
................FvSPEED_UP(33120).............. 23.15 fps k=140 a-v=27270 c-a=717641 u=10 d=0 pts=13612410
.............................. 30.27 fps k=141 a-v=21090 c-a=718809 u=10 d=0 pts=13706910
.............................. 30.24 fps k=142 a-v=16830 c-a=718627 u=10 d=0 pts=13801410
.............................. 30.05 fps k=143 a-v=12570 c-a=718520 u=10 d=0 pts=13895910
.............................. 30.08 fps k=144 a-v=8310 c-a=718330 u=10 d=0 pts=13990410
.............................. 30.13 fps k=145 a-v=4050 c-a=717973 u=10 d=0 pts=14084910
.......F....................vNORMAL... 29.19 fps k=146 a-v=2310 c-a=718581 u=10 d=0 pts=14178810
.............................. 30.01 fps k=147 a-v=2550 c-a=718566 u=10 d=0 pts=14268810
.............................. 30.12 fps k=148 a-v=2790 c-a=718195 u=10 d=0 pts=14358810
.............................. 30.10 fps k=149 a-v=3030 c-a=717923 u=10 d=0 pts=14448810
.............................. 30.10 fps k=150 a-v=3270 c-a=717623 u=10 d=0 pts=14538810
.............................. 30.20 fps k=151 a-v=3510 c-a=717434 u=10 d=0 pts=14632320
......F........................ 29.11 fps k=152 a-v=5670 c-a=718288 u=10 d=0 pts=14718810
.............................. 30.09 fps k=153 a-v=5910 c-a=718017 u=10 d=0 pts=14808810
.............................. 30.16 fps k=154 a-v=6150 c-a=717630 u=10 d=0 pts=14904960
.............................. 30.16 fps k=155 a-v=6390 c-a=717539 u=10 d=0 pts=14995200
.............................. 30.26 fps k=156 a-v=4710 c-a=718737 u=10 d=0 pts=15078810
.............................. 30.05 fps k=157 a-v=4950 c-a=718659 u=10 d=0 pts=15168810
.....F.vR104070........................ 14.55 fps k=158 a-v=-2880 c-a=718269 u=10 d=0 pts=15362880
.............................. 30.09 fps k=159 a-v=-2640 c-a=718025 u=10 d=0 pts=15452880
.............................. 30.12 fps k=160 a-v=-2400 c-a=717680 u=10 d=0 pts=15542880
.............................. 29.90 fps k=161 a-v=-2160 c-a=718003 u=10 d=0 pts=15630720
.............................. 30.39 fps k=162 a-v=-3840 c-a=718793 u=10 d=0 pts=15722880
.............................. 29.92 fps k=163 a-v=-1680 c-a=717569 u=10 d=0 pts=15811200
...F.vR95760.......................... 14.60 fps k=164 a-v=-3120 c-a=718438 u=10 d=0 pts=15998640
.............................. 30.10 fps k=165 a-v=-2880 c-a=718188 u=10 d=0 pts=16088640
.............................. 30.11 fps k=166 a-v=-2640 c-a=717886 u=10 d=0 pts=16178640
.............................. 30.14 fps k=167 a-v=-2400 c-a=717518 u=10 d=0 pts=16268640
.............................. 30.18 fps k=168 a-v=-4080 c-a=718918 u=10 d=0 pts=16358640
.............................. 29.98 fps k=169 a-v=-1920 c-a=717574 u=10 d=0 pts=16446720
.F............................. 29.39 fps k=170 a-v=240 c-a=718156 u=10 d=0 pts=16538640
.............................. 30.19 fps k=171 a-v=480 c-a=717568 u=10 d=0 pts=16628640
.............................. 29.99 fps k=172 a-v=720 c-a=717596 u=10 d=0 pts=16718640
.............................. 30.25 fps k=173 a-v=-960 c-a=718794 u=10 d=0 pts=16808640
