### ISSUE TITLE
Audio device switching it's id randomly

### ISSUE THREAD

**Issue by bostiko** [iizukanao/picam#184]
Hallo,
I don't know if this is the picam problem at all. Through the `arecord -l` I gained the hw address of my soundcard. But after each restart it switch randomly between hw1,0 and hw3,0. In this way the sound sometimes work and sometimes do not :(

This is the output of `arecord -l

**** List of CAPTURE Hardware Devices ****
card 1: CODEC [USB Audio CODEC], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
`

**Comment by iizukanao** [comment]
That's not the problem of picam. Please see here and use a device name instead. https://www.diyaudio.com/community/threads/how-can-i-make-my-alsa-card-to-use-the-fixed-number.368992/
