### ISSUE TITLE
libcamera0 update breaks latest 2.0.7 binary release

### ISSUE THREAD

**Issue by summrum** [iizukanao/picam#187]
Hi, it appears updating libcamer0 to 0~git20221018+7c855784-1 breaks the latest 2.0.7 binary release. After the libcamera0 update, picam reports that shared libraries libcamera.so.0 and libcamera-base.so.0 can not be found. Manually symlinking libcamera.so.0.0.1 and libcamera-base.so.0.0.1 to libcamera.so.0 and libcamera-base.so.0 gets the binary to execute, but ends in a segmentation fault:

Oct 21 12:46:52 picam kernel: vc4-drm soc:gpu: [drm] Cannot find any crtc or sizes
Oct 21 12:46:52 picam run_picam.sh[663]: created HLS directory: /run/shm/hls
Oct 21 12:46:53 picam run_picam.sh[663]: [0:00:21.592276918] [663]  INFO Camera camera_manager.cpp:293 libcamera v0.0.1+21-7c855784
Oct 21 12:46:53 picam run_picam.sh[663]: [0:00:21.708727282] [666]  WARN RPI raspberrypi.cpp:1297 Mismatch between Unicam and CamHelper for embedded data usage!
Oct 21 12:46:53 picam run_picam.sh[663]: [0:00:21.710746345] [666]  INFO RPI raspberrypi.cpp:1414 Registered camera /base/soc/i2c0mux/i2c@1/imx219@10 to Unicam device /dev/media3 and ISP device >
Oct 21 12:46:53 picam run_picam.sh[663]: [0:00:21.712301605] [663]  INFO Camera camera.cpp:1026 configuring streams: (0) 1920x1080-YUV420
Oct 21 12:46:53 picam run_picam.sh[663]: [0:00:21.713315980] [666]  INFO RPI raspberrypi.cpp:800 Sensor: /base/soc/i2c0mux/i2c@1/imx219@10 - Selected sensor format: 1920x1080-SBGGR10_1X10 - Sele>
Oct 21 12:46:53 picam run_picam.sh[652]: Segmentation fault

This also appears to have been noticed by another user in #186. I haven't had a chance yet to try manually compiling with the latest libcamera release to see if that fixes the issue.

Thank you.

**Comment by iizukanao** [comment]
The issue has been fixed in [version 2.0.8](https://github.com/iizukanao/picam/releases/tag/v2.0.8). Please use it.
