### ISSUE TITLE
Trying to run v2.0.8 binary release on the Raspberry Pi with Debian Buster gives missing libcamera.so.0.0.1 error

### ISSUE THREAD

**Issue by HWiese1980** [iizukanao/picam#189]
Title already says it mostly... If I'm trying to run picam on a Raspberry Pi with Debian Buster, I'm getting the following error message:

```bash
pi@raspberrypi:~/picam $ ./picam
./picam: error while loading shared libraries: libcamera.so.0.0.1: cannot open shared object file: No such file or directory
```

What can I do about that?

**Comment by iizukanao** [comment]
Did you install libcamera0 package? If not, please install it with `sudo apt install libcamera0`

**Comment by HWiese1980** [comment]
Yes. I'll reinstall it and see if it helps.

**Comment by HWiese1980** [comment]
Sad news, I've decided to mothball the project of a self-built surveillance camera for now, and purchased a cheap IP camera instead. All this tinkering to make it work was too much for my wife who just wanted a reliably working camera. So I'll probably not be able to pursue this topic further any time soon - not, unless I'll find another project that needs a dedicated IP camera.

I'm really sorry. I'll close this topic for now... if anyone else runs into the same issue, feel free to open it up again and add all the info that you have. Thanks!
