### ISSUE TITLE
Latency In receiving video with VLC

### ISSUE THREAD

**Issue by semofa** [iizukanao/picam#19]
HI,
I successfully install Picam and nginx-rtmp-module. I started streaming video as you said: 
  ./picam --tcpout tcp://127.0.0.1:8181
but when I get the video with VLC It has 3 sec latency. How can I remove the latency?

**Comment by iizukanao** [comment]
Hi, sorry for the late reply.
Use [Strobe Media Playback](http://sourceforge.net/adobe/smp/home/Strobe%20Media%20Playback/) as a client.
