### ISSUE TITLE
deamanorize picam

### ISSUE THREAD

**Issue by leifnagtegaal** [iizukanao/picam#190]
Hi,

starting picam from terminal with: `./picam/picam -o /run/shm/hls --alsadev hw:0,0 --channels 2 --samplerate 44100 --vflip` is working fine.
But now i like to have t to running automaticly and i tried to daemonize picam by following the readme of https://github.com/iizukanao/picam/tree/master/etc but unfortunately it is not working like epected.

Flowwing the readme I created the default config file and the deamon script, but after starting picam service manually nothing happens.
Are in the default script some neccesarry configuration changes which i missed? 

I can start it manually and the status returns then the following:
`pi@Picam:~ $ sudo service picam start
pi@Picam:~ $ sudo service picam status
● picam.service - LSB: picam
     Loaded: loaded (/etc/init.d/picam; generated)
     Active: active (exited) since Sun 2022-11-13 21:04:05 CET; 6s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 1233 ExecStart=/etc/init.d/picam start (code=exited, status=0/SUCC>
        CPU: 255ms

Nov 13 21:04:05 PiBear systemd[1]: Starting LSB: picam...
Nov 13 21:04:05 PiBear picam[1233]: creating /run/shm/hls directory
Nov 13 21:04:05 PiBear systemd[1]: Started LSB: picam.`

But its not possible to access the stream via http://picam.local/hls/index.m3u8

Do you have an idea, how i could get picam running with the deamon script which you have published?

Greetings
Leif

**Comment by iizukanao** [comment]
Ah sorry, the init.d script uses obsolete command line options.
Please remove the following lines from [PICAM_OPTIONS](https://github.com/iizukanao/picam/blob/master/etc/init.d/picam#L45-L54) in the init.d script.
- `--rotation $VIDEO_ROTATION \`
- `--qpmin $VIDEO_QPMIN \`
- `--qpmax $VIDEO_QPMAX \`
- `--qpinit $VIDEO_QPINIT \`

It may also be helpful to look at the picam error log.

**Comment by leifnagtegaal** [comment]
Hi Nao,
great thanks - now it is running deamonized!

**Comment by iizukanao** [comment]
Glad to hear that!
