### ISSUE TITLE
Libcamera0 0~git20221130+0684c373-1 breaks pre-built binary 2.0.8

### ISSUE THREAD

**Issue by summrum** [iizukanao/picam#193]
Hi, the latest libcamera0 update to 0~git20221130+0684c373-1 breaks the pre-built binary 2.0.8. I believe this closed issue #189 was likely due to the libcamera0 update.

I can confirm that a rebuild of picam against this latest version works without issue for me (armv7l).

Thank you.

**Comment by iizukanao** [comment]
Thank you for the detailed information. I will release a fixed version soon.

**Comment by iizukanao** [comment]
[Version 2.0.9](https://github.com/iizukanao/picam/releases/tag/v2.0.9) has been released to fix this issue.
