### ISSUE TITLE
./picam: error while loading shared libraries: libcamera-base.so.0.0.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by feacluster** [iizukanao/picam#198]
I am running Raspbian GNU/Linux 11 (bullseye) on a Pi4b. I installed picam 2.0.12 . When running I get the error:

./picam: error while loading shared libraries: libcamera-base.so.0.0.3: cannot open shared object file: No such file or directory

I was able to do the following workaround to get it to work:

```
sudo ln -s /lib/arm-linux-gnueabihf/libcamera.so.0.0.4 libcamera.so.0.0.3
sudo ln -s /lib/arm-linux-gnueabihf/libcamera-base.so.0.0.4 libcamera-base.so.0.0.3
```

**Comment by iizukanao** [comment]
Thank you for reporting this! I have just fixed the latest release files.
https://github.com/iizukanao/picam/releases/tag/v2.0.12
