### ISSUE TITLE
Picam.  Error loading shared directory libcamera.so.0.0.4

### ISSUE THREAD

**Issue by Tangerinedean** [iizukanao/picam#203]
Hi I am getting the above error when starting
Picam.It appears that I am actually running with libcamera.so.0.0.5 on Bullseye  64bit. Please could you advise ...

Thanks
Dean Rosindale

**Comment by iizukanao** [comment]
Hi Dean,

[The binary for version 2.0.12](https://github.com/iizukanao/picam/releases/tag/v2.0.12) has recently been updated. Please download it.
Also, please run `sudo apt-get update` and `sudo apt-get upgrade`.

**Comment by Tangerinedean** [comment]
All working now.
Thanks
Dean R
