### ISSUE TITLE
Rec folder duplication

### ISSUE THREAD

**Issue by Sdb-sign** [iizukanao/picam#206]
Hi, I am trying to use this with limited programming know how. I have managed to install and run it, but the rec folder is created with duplicates of the picam folder, and I am unable to delete the duplicates as they arent able to be found?

**Comment by iizukanao** [comment]
Hello,

I'm trying to fully grasp the situation you're encountering. It seems like there might be unintentional duplicates of the 'picam' folder within the 'rec' directory. If these duplicates were created by mistake and you wish to remove them, you can use the `rm -rf` command in the terminal. This command will forcefully remove the specified directories and their contents.

**Comment by Sdb-sign** [comment]
Hi, I managed to resolve this by deleting, rebooting and running the install process again.
