### ISSUE TITLE
Notify in case of invalid hooks

### ISSUE THREAD

**Issue by Humphreybas** [iizukanao/picam#21]
Hi,

Nice software, thank you!
One small request for the sleepy users:
please notify in the picam output when an invalid filename has been placed in the hooks directory.

I admit, it is quite stupid, but I spent a small hour trying to figuring out why picam didn't work on hooks/record_start while it was working fine yesterday. (it should have been start_record)

Thanks!
Thanks!

**Comment by iizukanao** [comment]
Hi, thanks for the nice suggestion!

With the latest master branch code, picam shows an error message when it receives an invalid hook command.

**Comment by Humphreybas** [comment]
Great, thanks! And again, thanks for sharing!
