### ISSUE TITLE
opacity preview?

### ISSUE THREAD

**Issue by yves72** [iizukanao/picam#25]
Hi,

I really like your picam package, as far as I know it works flawless!

I am controlling it with python, and i'm trying to combine it with pygame. So i want to show the screen and also have the preview shown on top.

with the default "raspivid" command you can set the opacity so you could see the pygamescreen at the same time.

I was wondering if you could also add it in your package?

Many thanks in advance!

Yves

**Comment by iizukanao** [comment]
Hi,

Sorry for the late reply!
I've just added `--opacity` option. Please check out the latest master.
