### ISSUE TITLE
Other Cameras

### ISSUE THREAD

**Issue by WeWin55** [iizukanao/picam#30]
Hello, 

first of all I want to thanks iizukanao for this nice program!
My only question is:
Can we use picam with other webcams (logitech c270 for example)?
Thanks

**Comment by iizukanao** [comment]
It's theoretically possible, but not supported by picam since it is not practical. USB bandwidth for Raspberry Pi is very limited and not capable of transferring large video stream. Raspberry Pi Camera is a much better option at this time.

**Comment by WeWin55** [comment]
Thank you for the fast answer!
