### ISSUE TITLE
streaming picam to remote node-rtsp-rtmp-server on the cloud

### ISSUE THREAD

**Issue by helxsz** [iizukanao/picam#57]
when installing picam and node-rtsp-rtmp-server server on the same PI platform, it works out by `./picam --rtspout ` that the picam automatically links the stream to the  node-rtsp-rtmp-server server on the pi. What if I have the node-rtsp-rtmp-server on a remote cloud server with certain IP address? what command I should use?

**Comment by iizukanao** [comment]
This is a duplicate of #58. Closing.
