### ISSUE TITLE
some options do not seem to have effect

### ISSUE THREAD

**Issue by voorm11** [iizukanao/picam#60]
First off all, thanks for the excellent work with Picam. I love it how it combines sound and video in one file. But playing with it, I have some options that not seem to work.

The options --ex <value> and --evcomp <num> do not seem to have any effect when I try to record some video. When I record a room in the evening with the lights on, the output with different values for these options are exactly the same as when I leave the options in the default value.

I am looking for a configuration to have the output recording a lot brighter in a normal lighted room in the evening. When I use the program http://elinux.org/RPi-Cam-Web-Interface, I get very good results with the options --ex backlight and --evcomp 8 (or 9 or 10),... But with PiCam the setting of these options do not have any effect.

I use:
./picam  --width 1920 --height 1080 --vfr --rotation 90 --videobitrate 4000000 --qpmin 12 --qpmax 24 --qpinit 12 --alsadev hw:1,0 --volume 3 --verbose --wb incandescent --metering matrix --iso 800 --avcprofile constrained_baseline --avclevel 3.1
... and of course the options --ex <value> and --evcomp <num> in different values.

and also tried:

./picam  --width 1280 --height 720 --rotation 90 --videobitrate 4000000 --qpmin 1 --qpmax 24 --qpinit 1 --alsadev hw:1,0 --volume 3 --verbose --wb incandescent --metering matrix --evcomp 10 --iso 800 --vfr
... and of course also the options --ex <value> and --evcomp <num> in different values.

I use a RPi3 with cam 2.1

Am I missing something?

Thx in advance,

Michel

**Comment by iizukanao** [comment]
@voorm11 Thank you for reporting the issue! I've just released a new version [1.4.5](https://github.com/iizukanao/picam/releases/tag/v1.4.5) and `--evcomp` bug has been fixed.

As for `--ex`, it seems we can't use both `--iso` and `--ex` at the same time. Remove `--iso` and use `--ex` instead.
