### ISSUE TITLE
ROI?

### ISSUE THREAD

**Issue by paolohu** [iizukanao/picam#67]
Is there anything in picam similar to the -roi (region of interest) functionality that exists in the raspivid app?

I am using a PiCapture HD1 board (emulates the camera) - my issue is certain resolutions (1080i for example) the full frame isn't video - so to work around it they recommend using -roi to pull the video.  It works fine for raspivid and it would be great if I could do something similar in picam.

thanks,

-paolo

**Comment by iizukanao** [comment]
@paolohu Implemented `--roi` option in version 1.4.6. Please give it a try!

**Comment by paolohu** [comment]
awesome - i'll give it a try today and let you know!

**Comment by paolohu** [comment]
yep this works great!  appreciate the quick turnaround!
