### ISSUE TITLE
Disable Video

### ISSUE THREAD

**Issue by skonagaya** [iizukanao/picam#77]
Hi,

Is there a way to disable video? Like _--noaudio_ but for video.

Thanks,
Sean

**Comment by iizukanao** [comment]
@skonagaya Why do you need it? You can record and stream audio with just ffmpeg.

**Comment by skonagaya** [comment]
Yep. Looks like that would work. 

Appreciate the reply.

**Comment by skonagaya** [comment]
I ended up using this command to stream audio only:

`ffmpeg -re -f alsa -i plughw:1,0 -acodec mp2 -ab 32k -ac 1  -f rtp rtp://destinationIP:8099`

The command above is ran on the source device (in my case an RPi). I retrieved the stream using VLC on the destination device with the network url _rtp://destinationIP:8099_.
