### ISSUE TITLE
Not working with crontab.

### ISSUE THREAD

**Issue by PrinceShaji** [iizukanao/picam#78]
I made a cronjob to run picam at startup, and it's running perfectly. But it's not recording videos. But when running picam from terminal, it's possible to record video. Looks like it only works when there is an open terminal that runs picam. Anyway to run picam at startup and still record files?

**Comment by iizukanao** [comment]
@PrinceShaji Add `cd /path/to/picam/dir &&` to the beginning of your cronjob. For example:

```
@reboot cd /home/pi/picam && ./picam
```

**Comment by PrinceShaji** [comment]
Sorry for the late reply. And Thanks.
