### ISSUE TITLE
Sample rate problem

### ISSUE THREAD

**Issue by jwadsager** [iizukanao/picam#9]
I have followed the instructions in the install and readme files to get picam built and working with nginx-rtmp, but when I run `picam --tcpout 127.0.0.1:8181` I get:

[libfdk_aac @ 0x1cd51c0] Specified sample rate 0 is not supported
avcodec_open failed

This problem exists both when picam is install manually on Arch Linux and on the provided Raspbian image (which is much appreciated).

Also, I would be very interested in support for 1920x1080. Currently the program fails when you start recording with that resolution.

**Comment by tylerjl** [comment]
Hi @iizukanao, thanks for this project, it looks great!

Unfortunately I seem to be having similar problems on my Arch Linux Pi, this is based off revision 28c54acaeeda8909e8913646e5b09d656b4fe50d in git:

```
./picam --noaudio
configuring devices
Sample format s16 is not supported
```

(I don't have an audio device.) Any ideas? I can provide additional info if needed.

**Comment by iizukanao** [comment]
@tylerjl Does [binary release](https://github.com/iizukanao/picam/releases/latest) produce the same error?

**Comment by tylerjl** [comment]
I actually had to compile it from source, at it seems Arch is shipping with a later version of libpng that the binary isn't linked against:

```
$ picam-1.4.1-binary/picam --help
picam-1.4.1-binary/picam: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
$ ls -l /usr/lib/libpng*
lrwxrwxrwx 1 root root     11 Jan 24 17:34 /usr/lib/libpng.so -> libpng16.so
lrwxrwxrwx 1 root root     19 Jan 24 17:34 /usr/lib/libpng16.so -> libpng16.so.16.21.0
lrwxrwxrwx 1 root root     19 Jan 24 17:34 /usr/lib/libpng16.so.16 -> libpng16.so.16.21.0
-rwxr-xr-x 1 root root 174108 Jan 24 17:34 /usr/lib/libpng16.so.16.21.0
```

**Comment by iizukanao** [comment]
@tylerjl Could you please create a new issue instead of this thread? The problem you are having is not related to the original issue.
