### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mitsus** [iizukanao/picam#97]
Hi, I try to compile picam.
I followed wiki, but i've this error:

`mpegts.c: In function â€˜setup_video_streamâ€™:
mpegts.c:46:37: error: â€˜CODEC_FLAG_GLOBAL_HEADERâ€™ undeclared (first use in this function)
   video_codec_ctx->flags         |= CODEC_FLAG_GLOBAL_HEADER;
                                     ^~~~~~~~~~~~~~~~~~~~~~~~
mpegts.c:46:37: note: each undeclared identifier is reported only once for each function it appears in
Makefile:29: recipe for target 'mpegts.o' failed
make: *** [mpegts.o] Error 1`

Can someone help me please?

Thanks

**Comment by iizukanao** [comment]
@mitsus Thank you for reporting this issue. It's now fixed.
